language: r
dist: xenial
cache: packages

os: 
  - linux

r_packages:
  - devtools
  - hunspell

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  # tcsh
  - sudo apt install tcsh
  - which tcsh
  # NetMHCIIpan
  - |
    Rscript -e "source(\"R/install_netmhc2pan.R\"); \
    source(\"R/capitalize_first_char.R\"); \
    source(\"R/get_default_netmhc2pan_bin_path.R\"); \
    source(\"R/get_default_netmhc2pan_folder.R\"); \
    source(\"R/get_default_netmhc2pan_subfolder.R\"); \
    source(\"R/get_netmhc2pan_url.R\"); \
    source(\"R/is_netmhc2pan_installed.R\"); \
    install_netmhc2pan()"
  - echo -e ">sp|L0T550|RIP2_MYCTU_158_180\nAVLWAGVAFLAFLQLTALVLNLL" > example.fasta
  - ~/.local/share/netMHCIIpan-3.2/netMHCIIpan -f example.fasta
  - rm example.fasta
  # proselint
  - sudo pip install proselint

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi

after_failure:
  - ls