# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 23 * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - install_netmhc2pan: "true" 
          - install_netmhc2pan: "false"

    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Show NETMHC2PAN
        env:
          INSTALL_NETMHC2PAN: ${{ matrix.install_netmhc2pan }}
        run: echo "$INSTALL_NETMHC2PAN"

      - name: If statement on NETMHC2PAN is true
        env:
          INSTALL_NETMHC2PAN: ${{ matrix.install_netmhc2pan }}
        run: if [[ "$INSTALL_NETMHC2PAN" == true ]]; then echo "Yay!"; fi

      - name: Show location
        run: pwd

      - name: If statement on NETMHC2PAN is false
        env:
          INSTALL_NETMHC2PAN: ${{ matrix.install_netmhc2pan }}
        run: if [[ "$INSTALL_NETMHC2PAN" == false ]]; then echo "Nay!"; fi

      - name: Show NETMHC2PAN install script
        env:
          INSTALL_NETMHC2PAN: ${{ matrix.install_netmhc2pan }}
        run: if [[ "$INSTALL_NETMHC2PAN" == true ]]; then cat scripts/install_netmhc2pan.sh; fi

      - name: Install NETMHC2PAN
        env:
          INSTALL_NETMHC2PAN: ${{ matrix.install_netmhc2pan }}
        run: if [[ "$INSTALL_NETMHC2PAN" == true ]]; then ./scripts/install_netmhc2pan.sh; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: if [[ "$INSTALL_NETMHC2PAN" == true ]]; then Rscript -e 'covr::codecov()'; fi

      - name: Lint
        run: if [[ "$INSTALL_NETMHC2PAN" == false ]]; then Rscript -e 'lintr::lint_package()'; fi

